#!/bin/bash
# 1st arg = .dots file
# 2nd arg = output executable

set -e 
./dotc < $1 > $1.c

OUT_FILE=$2

if [ -z "$2" ]; then
    OUT_FILE="exec"
fi

# gcc -I ${DOTS} -o exec file.c -L${DOTS} -ldots
gcc $1.c -I ${DOTS} -L${DOTS} -ldots -o ${OUT_FILE}
